name: build docker image multi-arch via buildx

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          skip-cache: false
          qemu-version: latest
      - name: list available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build the image
        run: |
          docker buildx build --push \
            --tag vincentds/reactive-hass:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
